version = "1.0"

[main]
name.en = "Juliaup"

[main.status]
name.en = "Installed versions"

[main.status.installed_versions]
type = "text"
ask.en = "Installed Julia versions"
help.en = "Refresh this page to update the list."
readonly = true
bind = "null"

[main.add]
name.en = "Install a version"

[main.add.add_version]
type = "string"
ask.en = "Version or channel"
example = "lts"
bind = "null"

[main.add.add]
type = "button"
ask.en = "Install"
style = "success"
icon = "plus"
bind = "null"

[main.remove]
name.en = "Remove a version"

[main.remove.remove_version]
type = "string"
ask.en = "Version or channel"
example = "1.10"
bind = "null"

[main.remove.remove]
type = "button"
ask.en = "Remove"
style = "danger"
icon = "trash"
bind = "null"

[main.default]
name.en = "Set default version"

[main.default.default_version]
type = "string"
ask.en = "Version or channel"
example = "1.11"
bind = "null"

[main.default.default]
type = "button"
ask.en = "Set default"
style = "warning"
icon = "star"
bind = "null"

[main.update]
name.en = "Update"

[main.update.update_versions]
type = "button"
ask.en = "Update installed Julia versions"
style = "success"
icon = "refresh"
bind = "null"

[main.update.update_juliaup]
type = "button"
ask.en = "Update juliaup"
style = "info"
icon = "download"
bind = "null"
