version = "1.0"

[main]
name = "Juliaup"

[main.status]
name = "Installed versions"
help = "Refresh this page to update the list."

[main.status.installed_versions]
type = "text"
ask = "Installed Julia versions"
readonly = true
bind = "null"

[main.add]
name = "Install a version"

[main.add.add_version]
type = "string"
ask = "Version or channel"
example = "lts"
bind = "null"

[main.add.add]
type = "button"
ask = "Install"
style = "success"
icon = "plus"
bind = "null"

[main.remove]
name = "Remove a version"

[main.remove.remove_version]
type = "string"
ask = "Version or channel"
example = "1.10"
bind = "null"

[main.remove.remove]
type = "button"
ask = "Remove"
style = "danger"
icon = "trash"
bind = "null"

[main.default]
name = "Set default version"

[main.default.default_version]
type = "string"
ask = "Version or channel"
example = "1.11"
bind = "null"

[main.default.default]
type = "button"
ask = "Set default"
style = "warning"
icon = "star"
bind = "null"

[main.update]
name = "Update"

[main.update.update_versions]
type = "button"
ask = "Update installed Julia versions"
style = "success"
icon = "refresh"
bind = "null"

[main.update.update_juliaup]
type = "button"
ask = "Update juliaup"
style = "info"
icon = "download"
bind = "null"

[main.update.update_environment]
type = "button"
ask = "Update Julia environment"
style = "info"
icon = "flask"
bind = "null"
