packaging_format = 2

id = "julia"
name = "Julia (via juliaup)"
description.en = "Julia programming language installed via juliaup version manager"
version = "1.0.0~ynh45"
maintainers = ["Azzaare"]

[upstream]
license = "MIT"
website = "https://julialang.org"
code = "https://github.com/JuliaLang/juliaup"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = ["amd64","arm64"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "500M"
ram.build = "256M"
ram.runtime = "128M"

[resources]

[resources.system_user]
home = "/var/lib/__APP__"

[resources.apt]
packages = ["curl", "ca-certificates"]
