#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

if [ -d "$install_dir/.juliaup" ]; then
  ynh_backup "$install_dir/.juliaup"
fi

if [ -d "$install_dir/.julia" ]; then
  ynh_backup "$install_dir/.julia"
fi
