#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

if [ -d "/home/$app/.juliaup" ]; then
  ynh_backup "/home/$app/.juliaup"
fi

if [ -d "/home/$app/.julia" ]; then
  ynh_backup "/home/$app/.julia"
fi
