#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

# Ensure home exists for juliaup
mkdir -p "/home/$app"
chown -R "$app:$app" "/home/$app"

sudo -u "$app" -H bash << 'EOF'
curl -fsSL https://install.julialang.org | sh -s -- -y
EOF

cat > "/etc/profile.d/$app.sh" << EOF
export PATH="/home/$app/.juliaup/bin:$PATH"
EOF

sudo -u "$app" -H "$juliaup_bin" status
