#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

ynh_safe_rm "/etc/profile.d/$app.sh"

# Remove global launcher if this is the primary instance
if [ "$app" = "julia" ]; then
  ynh_safe_rm "/usr/local/bin/julia"
  ynh_safe_rm "/usr/local/bin/juliaup"
fi
