#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

rm -f "/etc/profile.d/$app.sh"

# Remove global launcher if this is the primary instance
if [ "$app" = "julia" ]; then
  rm -f "/usr/local/bin/julia"
fi
