#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

ynh_restore_file --origin_path="$install_dir/.juliaup" --not_mandatory
ynh_restore_file --origin_path="$install_dir/.julia" --not_mandatory

if [ -d "$install_dir/.juliaup" ]; then
  chown -R "$app:$app" "$install_dir/.juliaup"
fi

if [ -d "$install_dir/.julia" ]; then
  chown -R "$app:$app" "$install_dir/.julia"
fi

ensure_juliaup_permissions
deploy_julia_shell_files
