#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/_common.sh"

if [ -d "/home/$app" ] && [ ! -e "$install_dir/.juliaup" ]; then
  ynh_print_info "Migrating data directory from /home/$app to $install_dir"
  if [ ! -d "$install_dir" ]; then
    mv "/home/$app" "$install_dir"
  else
    cp -a "/home/$app/." "$install_dir/"
    ynh_safe_rm "/home/$app"
  fi
  chown -R "$app:$app" "$install_dir"
fi

ynh_app_setting_set --app="$app" --key=install_dir --value="$install_dir"

if [ ! -x "$juliaup_bin" ]; then
  ynh_print_info "juliaup not found in $install_dir, installing..."
  _juliaup_install
fi

ynh_script_progression "Updating juliaup channels..."
_juliaup_exec self update
_juliaup_exec update

ynh_script_progression "Fixing shared Julia permissions..."
ensure_juliaup_permissions
