#!/bin/bash
set -eu

# shellcheck disable=SC1090
source "$(dirname "$0")/../_common.sh"

version="${1:-}"
if [ -z "$version" ]; then
  echo "Missing version argument" >&2
  exit 1
fi

sudo -u "$app" -H "$juliaup_bin" add "$version"
